source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 1.2'
pod "RBStoryboardLink", "0.1.0"
pod 'FlatUIColors'
pod 'Persei', '~> 1.0.1'
pod 'Player'
pod 'GradientCircularProgress', :git => 'https://github.com/keygx/GradientCircularProgress'
pod 'KYCircularProgress'
pod 'Spring', '~> 1.0.3'
pod 'SwiftRecord'
pod "SwiftCSV"
pod "SnapKit"
pod 'HanekeSwift'
pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'
